CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    Email NVARCHAR(256) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(512) NULL,
    DisplayName NVARCHAR(160) NOT NULL,
    Role NVARCHAR(40) NOT NULL DEFAULT 'Student',
    EmailVerifiedAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    DeletedAt DATETIME2 NULL
);

CREATE TABLE RefreshTokens (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    TokenHash NVARCHAR(512) NOT NULL,
    ExpiresAt DATETIME2 NOT NULL,
    RevokedAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_RefreshTokens_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE LearningProfiles (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL UNIQUE,
    Goal NVARCHAR(300) NULL,
    Level NVARCHAR(80) NULL,
    LearningStyle NVARCHAR(80) NULL,
    DailyMinutes INT NOT NULL DEFAULT 25,
    PreferredStudyTime NVARCHAR(40) NULL,
    CONSTRAINT FK_LearningProfiles_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Documents (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    OwnerId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(240) NOT NULL,
    FileType NVARCHAR(40) NOT NULL,
    StorageUrl NVARCHAR(800) NULL,
    SourceUrl NVARCHAR(800) NULL,
    Status NVARCHAR(40) NOT NULL DEFAULT 'Pending',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    DeletedAt DATETIME2 NULL,
    CONSTRAINT FK_Documents_Users FOREIGN KEY (OwnerId) REFERENCES Users(Id)
);

CREATE TABLE DocumentChunks (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    DocumentId UNIQUEIDENTIFIER NOT NULL,
    ChunkIndex INT NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    EmbeddingId NVARCHAR(120) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_DocumentChunks_Documents FOREIGN KEY (DocumentId) REFERENCES Documents(Id)
);

CREATE TABLE FlashcardDecks (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    OwnerId UNIQUEIDENTIFIER NOT NULL,
    SourceDocumentId UNIQUEIDENTIFIER NULL,
    Title NVARCHAR(240) NOT NULL,
    Topic NVARCHAR(160) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    DeletedAt DATETIME2 NULL,
    CONSTRAINT FK_FlashcardDecks_Users FOREIGN KEY (OwnerId) REFERENCES Users(Id),
    CONSTRAINT FK_FlashcardDecks_Documents FOREIGN KEY (SourceDocumentId) REFERENCES Documents(Id)
);

CREATE TABLE Flashcards (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    DeckId UNIQUEIDENTIFIER NOT NULL,
    Question NVARCHAR(MAX) NOT NULL,
    Answer NVARCHAR(MAX) NOT NULL,
    Hint NVARCHAR(MAX) NULL,
    Explanation NVARCHAR(MAX) NULL,
    Difficulty NVARCHAR(40) NOT NULL DEFAULT 'Medium',
    Tag NVARCHAR(120) NULL,
    Source NVARCHAR(400) NULL,
    Topic NVARCHAR(160) NULL,
    ConfidenceScore DECIMAL(5,2) NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    DeletedAt DATETIME2 NULL,
    CONSTRAINT FK_Flashcards_Decks FOREIGN KEY (DeckId) REFERENCES FlashcardDecks(Id)
);

CREATE TABLE ReviewSchedules (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    FlashcardId UNIQUEIDENTIFIER NOT NULL,
    Repetition INT NOT NULL DEFAULT 0,
    EaseFactor DECIMAL(5,2) NOT NULL DEFAULT 2.50,
    IntervalDays INT NOT NULL DEFAULT 0,
    DueAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    LastReviewedAt DATETIME2 NULL,
    ForgetCount INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_ReviewSchedules_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT FK_ReviewSchedules_Flashcards FOREIGN KEY (FlashcardId) REFERENCES Flashcards(Id)
);

CREATE TABLE Quizzes (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    OwnerId UNIQUEIDENTIFIER NOT NULL,
    SourceDocumentId UNIQUEIDENTIFIER NULL,
    Title NVARCHAR(240) NOT NULL,
    Difficulty NVARCHAR(40) NOT NULL DEFAULT 'Medium',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    DeletedAt DATETIME2 NULL,
    CONSTRAINT FK_Quizzes_Users FOREIGN KEY (OwnerId) REFERENCES Users(Id),
    CONSTRAINT FK_Quizzes_Documents FOREIGN KEY (SourceDocumentId) REFERENCES Documents(Id)
);

CREATE TABLE QuizQuestions (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    QuizId UNIQUEIDENTIFIER NOT NULL,
    Type NVARCHAR(60) NOT NULL,
    Prompt NVARCHAR(MAX) NOT NULL,
    OptionsJson NVARCHAR(MAX) NULL,
    CorrectAnswer NVARCHAR(MAX) NOT NULL,
    Explanation NVARCHAR(MAX) NULL,
    Points INT NOT NULL DEFAULT 1,
    CONSTRAINT FK_QuizQuestions_Quizzes FOREIGN KEY (QuizId) REFERENCES Quizzes(Id)
);

CREATE TABLE QuizAttempts (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    QuizId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Score DECIMAL(5,2) NOT NULL DEFAULT 0,
    Accuracy DECIMAL(5,2) NOT NULL DEFAULT 0,
    DurationSeconds INT NOT NULL DEFAULT 0,
    StartedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CompletedAt DATETIME2 NULL,
    CONSTRAINT FK_QuizAttempts_Quizzes FOREIGN KEY (QuizId) REFERENCES Quizzes(Id),
    CONSTRAINT FK_QuizAttempts_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE QuizAnswers (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    AttemptId UNIQUEIDENTIFIER NOT NULL,
    QuestionId UNIQUEIDENTIFIER NOT NULL,
    Answer NVARCHAR(MAX) NOT NULL,
    IsCorrect BIT NOT NULL,
    ResponseTimeMs INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_QuizAnswers_Attempts FOREIGN KEY (AttemptId) REFERENCES QuizAttempts(Id),
    CONSTRAINT FK_QuizAnswers_Questions FOREIGN KEY (QuestionId) REFERENCES QuizQuestions(Id)
);

CREATE TABLE AiConversations (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(240) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_AiConversations_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE AiMessages (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ConversationId UNIQUEIDENTIFIER NOT NULL,
    Role NVARCHAR(40) NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    Model NVARCHAR(120) NULL,
    Tokens INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_AiMessages_Conversations FOREIGN KEY (ConversationId) REFERENCES AiConversations(Id)
);

CREATE TABLE StudyGoals (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(240) NOT NULL,
    Deadline DATETIME2 NULL,
    Status NVARCHAR(40) NOT NULL DEFAULT 'Active',
    CONSTRAINT FK_StudyGoals_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE RoadmapItems (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    GoalId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(240) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    StartAt DATETIME2 NULL,
    DueAt DATETIME2 NULL,
    Status NVARCHAR(40) NOT NULL DEFAULT 'Pending',
    SortOrder INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_RoadmapItems_Goals FOREIGN KEY (GoalId) REFERENCES StudyGoals(Id)
);

CREATE TABLE StudySessions (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(240) NOT NULL,
    SessionType NVARCHAR(60) NOT NULL,
    StartedAt DATETIME2 NOT NULL,
    EndedAt DATETIME2 NULL,
    FocusMinutes INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_StudySessions_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE GamificationProfiles (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL UNIQUE,
    Xp INT NOT NULL DEFAULT 0,
    Coins INT NOT NULL DEFAULT 0,
    Energy INT NOT NULL DEFAULT 100,
    CurrentStreak INT NOT NULL DEFAULT 0,
    League NVARCHAR(80) NULL,
    CONSTRAINT FK_GamificationProfiles_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Classes (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    TeacherId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(240) NOT NULL,
    Subject NVARCHAR(160) NULL,
    InviteCode NVARCHAR(40) NOT NULL UNIQUE,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Classes_Teachers FOREIGN KEY (TeacherId) REFERENCES Users(Id)
);

CREATE TABLE ClassMembers (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ClassId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    MemberRole NVARCHAR(40) NOT NULL DEFAULT 'Student',
    JoinedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ClassMembers_Classes FOREIGN KEY (ClassId) REFERENCES Classes(Id),
    CONSTRAINT FK_ClassMembers_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Assignments (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ClassId UNIQUEIDENTIFIER NOT NULL,
    CreatedById UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(240) NOT NULL,
    AssignmentType NVARCHAR(60) NOT NULL,
    TargetId UNIQUEIDENTIFIER NULL,
    DueAt DATETIME2 NULL,
    CONSTRAINT FK_Assignments_Classes FOREIGN KEY (ClassId) REFERENCES Classes(Id),
    CONSTRAINT FK_Assignments_Users FOREIGN KEY (CreatedById) REFERENCES Users(Id)
);

CREATE TABLE AiGenerationJobs (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    DocumentId UNIQUEIDENTIFIER NULL,
    JobType NVARCHAR(80) NOT NULL,
    Status NVARCHAR(40) NOT NULL DEFAULT 'Pending',
    ErrorMessage NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CompletedAt DATETIME2 NULL,
    CONSTRAINT FK_AiGenerationJobs_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT FK_AiGenerationJobs_Documents FOREIGN KEY (DocumentId) REFERENCES Documents(Id)
);

CREATE TABLE AuditLogs (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NULL,
    Action NVARCHAR(160) NOT NULL,
    EntityType NVARCHAR(120) NULL,
    EntityId UNIQUEIDENTIFIER NULL,
    IpAddress NVARCHAR(80) NULL,
    MetadataJson NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_AuditLogs_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE INDEX IX_Flashcards_DeckId ON Flashcards(DeckId);
CREATE INDEX IX_ReviewSchedules_User_Due ON ReviewSchedules(UserId, DueAt);
CREATE INDEX IX_QuizAttempts_User ON QuizAttempts(UserId);
CREATE INDEX IX_AiMessages_Conversation ON AiMessages(ConversationId);
CREATE INDEX IX_DocumentChunks_Document ON DocumentChunks(DocumentId);

